title: Metafields Values
type: object
description: "(Optional) A set of key/value pairs representing custom fields and their values. Metafields will be created “on-the-fly” in your site for a given key, if they have not been created yet."
additionalProperties:
  type: string
example:
  custom_field_name_1: "custom_field_value_1"
  custom_field_name_2: "custom_field_value_2"
